config/routes.rb
require 'sidekiq/web'
require 'sidekiq/cron/web'

Rails.application.routes.draw do
  mount Sidekiq::Web => '/sidekiq'

  root 'movies#index'

  devise_for :users
  resources :users, only: %i[index show edit update] do
    member do
      put :toggle_account_status
    end
  end

  resources :movies do
    collection do
      get :autocomplete
    end
    member do
      put :add_to_watch_later
    end
    member do
      get :watch_later
    end
    member do
      delete :destroy_watch_later
    end
    resources :reviews
  end

  namespace :admin do
    resources :movies do
      member do
        patch :refresh
      end
    end
  end

  namespace :api do
    resources :movies
  end
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :bigint           not null, primary key
#  active                 :boolean          default(TRUE)
#  confirmation_sent_at   :datetime
#  confirmation_token     :string
#  confirmed_at           :datetime
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  nickname               :string
#  remember_created_at    :datetime
#  reset_password_sent_at :datetime
#  reset_password_token   :string
#  role                   :integer          default("customer")
#  unconfirmed_email      :string
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#
# Indexes
#
#  index_users_on_email                 (email) UNIQUE
#  index_users_on_reset_password_token  (reset_password_token) UNIQUE
#

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable

  enum role: %i[admin customer]

  has_many :reviews, dependent: :destroy
  has_and_belongs_to_many :movies, dependent: :destroy
  has_one_attached :profile_image

  validates :nickname,
            presence: true,
            uniqueness: true,
            format: { with: /\A[a-zA-Z0-9]+\z/, message: 'only allows letters and numbers' }

  def save_movie?(movie:)
    if movies.include?(movie)
      false
    else
      movies << movie
    end
  end

  def active_for_authentication?
    super && active
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  def index
    @users = User.all
    authorize @users
  end

  def show
    @user = user
    authorize @user
  end

  def edit
    @user = user
    authorize @user
  end

  def update
    @user = user
    authorize @user
    if @user.update(user_params)
      redirect_to users_path
    else
      render :edit
    end
  end

  def toggle_account_status
    @user = user
    authorize @user
    @user.toggle!(:active)
    redirect_to users_path
  end

  protected

  def user
    User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:nickname, :email, :password, :password_confirmation, :profile_image, :role)
  end
end

app/views/users/edit.html.slim
.container
  .user-image-for-edit
    - if @user.profile_image.attached?
      = image_tag(@user.profile_image.variant(resize: '240x240'))
    - else
      = image_tag("default-user-icon-8.jpg", height: 220, widht: 140)
  .col-md-6
    = simple_form_for(@user) do |f|
      = f.input :profile_image, as: :file
      = f.input :nickname
      p
        strong User roles:
        = f.select :role, User.roles.keys.map { |role| [role.titleize, role] }, {}, {:class => 'form-control'}
      = link_to 'Back', users_path, class: "btn btn-primary", role: "button"
      | &nbsp
      = f.button :submit, 'Update', class: "btn btn-primary"
    br

app/views/users/index.html.slim
.container.mt-4
  .table-responsive
    h3 Users list:
    table.table.table-hover.mt-2
      thead.thead-inverse
        tr
          th scope="col"  User
          th scope="col"  User nick
          th scope="col"  User role
          th scope="col"  User email
          th scope="col"  Account create
          th scope="col" 
          th scope="col" 
          th scope="col" 
      tbody.tcontent
        - @users.each do |user|
          tr
            td
              - if user.profile_image.attached?
                = image_tag(user.profile_image.variant(resize: '120x120'))
              - else
                = image_tag("default-user-icon-8.jpg", height: 110, widht: 110)
            td= user.nickname
            td= user.role
            td= user.email
            td= user.created_at.strftime("%d.%m.%Y")
            td= link_to 'Edit', edit_user_path(user), class: "btn btn-warning", role: "button"
            td= link_to user.active ? 'Block' : 'Unblock',
                    toggle_account_status_user_path(user), method: :put,
                    data: {confirm: user.active ? "User:#{user.nickname} is blocked" : "User:#{user.nickname} is unblocked" },
                    class:"btn btn-warning",
                    role:"button"
            td

app/views/users/show.html.slim
.container
  .well.well-sm
    .row
      .col-sm-6.col-md-4
        - if @user.profile_image.attached?
          = image_tag(@user.profile_image.variant(resize: '350x500'), class: "user-image-for-show")
        - else
          = image_tag("default-user-icon-8.jpg", height: 220, widht: 140)
      .col-sm-6.col-md-8
        h2
          strong= @user.nickname
        br
        p
          strong Email:
          = @user.email
        p
          strong Created:
          = @user.created_at.strftime("%d.%m.%Y")
        - unless @user.updated_at.nil?
          p
            strong Updated:
            = @user.updated_at.strftime("%d.%m.%Y")
      .show-button-group
        = link_to 'Edit', edit_user_registration_path(@user), class: "btn btn-primary", role: "button"
        | &nbsp
        = link_to 'Back', root_path, class: "btn btn-primary", role: "button"