config/routes.rb
require 'sidekiq/web'
require 'sidekiq/cron/web'

Rails.application.routes.draw do
  mount Sidekiq::Web => '/sidekiq'

  root 'movies#index'

  devise_for :users
  resources :users, only: %i[index show edit update] do
    member do
      put :toggle_account_status
    end
  end

  resources :movies do
    collection do
      get :autocomplete
    end
    member do
      put :add_to_watch_later
    end
    member do
      get :watch_later
    end
    member do
      delete :destroy_watch_later
    end
    resources :reviews
  end

  namespace :admin do
    resources :movies do
      member do
        patch :refresh
      end
    end
  end

  namespace :api do
    resources :movies
  end
end

app/views/shared/_footer.html.slim
footer.footer
  .container
    span
      | © 2019 Copyright:
    = link_to 'Movies catalog', root_path, class: "footer-link"

app/views/shared/_navbar.html.slim
nav.navbar.navbar-inverse.navbar-fixed-top
  .container-fluid
    .navbar-header
      = link_to 'Movies catalog', root_path, class: "navbar-brand"
    - if user_signed_in?
      #myNavbar.collapse.navbar-collapse
        ul.nav.navbar-nav
          li class="#{active_class(root_path)}" 
            = link_to 'Home', root_path
          li class="#{active_class(watch_later_movie_path(current_user.id))}" 
            = link_to 'Watch later', watch_later_movie_path(current_user.id)
          - if current_user.admin?
            li class="#{active_class(admin_movies_path)}" 
              = link_to 'Movies page', admin_movies_path
            li class="#{active_class(users_path)}" 
              = link_to 'Users page', users_path
        ul.nav.navbar-nav.navbar-right
          li class="#{active_class(user_path(current_user))}" 
            = link_to current_user.nickname, user_path(current_user)
          li
            = link_to destroy_user_session_path, method: :delete do
              span.glyphicon.glyphicon-log-out
              | Log out
    - else
      ul.nav.navbar-nav.navbar-right
        li
          = link_to new_user_registration_path do
            span.glyphicon.glyphicon-user
            | Sign Up
        li
          = link_to new_user_session_path do
            span.glyphicon.glyphicon-log-in
            | Login

app/views/shared/_search_form.slim
= form_tag(path, :method => "get", class: "form-horizontal" ) do
  .col-sm-4
    = text_field_tag :title,
                        nil, 
                        class: "form-control",
                        id: 'movies_serch',
                        autocomplete: :off,
                        placeholder: "Put title of movie "

  = submit_tag("Search", class: "btn btn-primary")